
### @name="PLACE PRODUCT"
POST http://localhost:8080/api/orders
Accept:application/json
Content-Type:application/json

{
  "customer": { "email": "rita@adobe.com"},
  "items": [
    {"product": {"id": 3}, "qty": 1},
    {"product": {"id": 1}, "qty": 2}
  ]
}